spring:
  application:
    name: graph
  datasource:
    url: jdbc:postgresql://localhost:5432/db_graph
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  graphql:
    graphiql:
      enabled: true

server:
  port: 7777
